[project]
name = "estresim"
version = "0.1.0"
description = "A Python interface for the EstreSim network simulator"
dependencies = [
	"meson==1.8.3"
	"pybind11"
]

[build-system]
requires = ["meson-python", "pybind11", "simgrid"]
build-backend = "mesonpy"

[tool.meson-python.args]
dist = ['--include-subprojects']
